### PR TITLE
remove key serialization, construct conn from ipnet.PSK

### PR DESCRIPTION
**Pull request by marten-seemann**
https://github.com/libp2p/go-libp2p-core/pull/118 removes the `ipnet.Protector` interfaces and replaces it by an `ipnet.PSK` (which is a named type for `[]byte`). Arguably, serialization of keys to a format that's storable on disk (and the corresponding deserialization) doesn't belong into libp2p, but should be the responsibility of the application using libp2p.

Therefore, this PR removes all serialization and deserialization functions. I will move them to IPFS in another PR.

Tracking issue: https://github.com/libp2p/go-libp2p/issues/795.

### CODE REVIEW

**Comment by Stebalien** [comment]
*comment moved to https://github.com/libp2p/go-libp2p/issues/795#issuecomment-591728718*

**Review by Stebalien — APPROVED** [review]
LGTM

**Comment by Stebalien** [comment]
Let's leave off merging this till everything is ready.

**Comment by Stebalien** [comment]
Any idea why the tests are failing?

**Comment by marten-seemann** [comment]
@Stebalien All the PRs listed in https://github.com/libp2p/go-libp2p/issues/795 should be ready for merging.
The CI is failing because go-libp2p-core changed the PSK type.

**Pull request merged**
