### PR TITLE
Added NewProtectorFromBytes wrapper

### PR DESCRIPTION
**Pull request by dgrisham**
Added function `NewProtectorFromBytes()` that accepts a byte slice, creates a v1psk out of it, then uses the v1psk to create a `Protector`. This makes it easy for implementations to pass their own random psk to create a `Protector` without having to format the corresponding the v1psk themselves.

I implemented this in the way that seemed to make the most sense, and didn't include any tests because the important bits were already tested. None of the changes should break anything, I simply modularized the code a bit more and added this function. However, let me know if there's something I should add/change (e.g. tests, function names).

Thanks!

### CODE REVIEW

**Comment by dgrisham** [comment]
Pinging @hsanjuan for any thoughts

**Comment by Kubuxu** [comment]
It would make more sense to check if slice provided is 32 bytes, copy it into array and just create new structure. Much simpler I think than creating storage structure and then decoding it again.

**Comment by Kubuxu** [comment]
See #11

**Review by hsanjuan — COMMENTED** [review]
Also, way more explicit to do `NewProtectorWithKey(key [32]byte)`. Immediately shows:

* It's not just some input, it's the key that you are passing
* It MUST be 32byte

**Comment by Kubuxu** [comment]
@hsanjuan I did all of that in #11 

I will close this one, @dgrisham thanks for the effort.

**Comment by hsanjuan** [comment]
@Kubuxu can you gx-release this? thanks!

**Comment by Kubuxu** [comment]
Done.

**Pull request closed without merging**
